# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1e1b4f9d994e9cfb6ac1c23add781340342c7d81e30f47616f6dbe6de734afc283a506a9b234ef0e90c5375daa5640ec5797a0f0a2054954f35371d19fe3848

test:
  secret_key_base: 49af360afd00de68a09f7a93760cb37478f678f0f977449e6c15e81c3ca672e4d2fef3c892b08714a5f11d0fabc0a50f453d3e7cafe7d29924a807f33bb53e2e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
